apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # <https://github.com/k3s-io/k3s/discussions/2997#discussioncomment-7966622>
    service:
      spec:
        externalTrafficPolicy: Local
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    # <https://k3s.rocks/install-setup/#install-k3s>
    logs:
      level: INFO
      access:
        enabled: true
