apiVersion: v1
kind: Service
metadata:
  name: syncthing-peer
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22000
  type: LoadBalancer
