apiVersion: v1
kind: Service
metadata:
  name: syncthing-admin
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
  type: ClusterIP
