apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: quay.io/hedgedoc/hedgedoc:1.10.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 750m
            memory: 768Mi
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: {{ .Chart.Name }}-data
          mountPath: /app/.assets
          readOnly: false
        envFrom:
        - secretRef:
            name: {{ .Release.Namespace }}-secrets
        - configMapRef:
            name: {{ .Release.Namespace }}-config
        env:
        - name: NEXT_ENV_IMAGES_ALL_REMOTE
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: {{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc
