apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  name: {{ .Chart.Name }}-server
spec:
  rules:
  - host: data.alifyasa.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - data.alifyasa.com
    secretName: tls-{{ .Chart.Name }}
