apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-secrets
type: Opaque
stringData:
  CMD_DB_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Namespace }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: |-
    {{ $value }}
  {{- end }}
