teable:
  env:
    PUBLIC_ORIGIN: "https://data.alifyasa.com"
    TEABLE_SECRET_KEY: PleaseChangeThis
    # <https://help.teable.io/developer/openid-connect#example-using-authentik-as-oidc-provider>
    BACKEND_OIDC_CLIENT_ID: authentik_client_id
    BACKEND_OIDC_CLIENT_SECRET: authentik_client_secret
    BACKEND_OIDC_CALLBACK_URL: "https://data.alifyasa.com/api/auth/oidc/callback"
    BACKEND_OIDC_USER_INFO_URL: "https://auth.alifyasa.com/application/o/userinfo/"
    BACKEND_OIDC_TOKEN_URL: "https://auth.alifyasa.com/application/o/token/"
    BACKEND_OIDC_AUTHORIZATION_URL: "https://auth.alifyasa.com/application/o/authorize/"
    BACKEND_OIDC_ISSUER: "https://auth.alifyasa.com/application/o/teable/"
    # For some reason yaml tried to parse a json string EVEN when fully escaped, 
    # multiline string is somehow a fix
    BACKEND_OIDC_OTHER: |-
      {"scope": ["email", "profile", "openid"]}
    SOCIAL_AUTH_PROVIDERS: oidc
redis:
  auth:
    password: PleaseChangeThis
postgresql:
  auth:
    enablePostgresUser: false
    username: teable
    password: PleaseChangeThis
    database: teable
  primary:
    resources:
      limits:
        memory: 4096Mi
        cpu: 2000m
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      size: 64Gi
    pgHbaConfiguration: |-
      # Unix sockets
      local   all  postgres   trust
      local   all  all        peer
      
      host    all  all        127.0.0.0/8    trust

      host    all  all        10.0.0.0/8     scram-sha-256
      host    all  all        172.16.0.0/12  scram-sha-256
      host    all  all        192.168.0.0/16 scram-sha-256

    configuration: |-
      # FINE TUNING (https://pgtune.leopard.in.ua)
      # DB Version: 15
      # OS Type: linux
      # DB Type: oltp
      # Total Memory (RAM): 4096 MB
      # CPUs num: 2
      # Data Storage: ssd

      max_connections = 300
      shared_buffers = 1GB
      effective_cache_size = 3GB
      maintenance_work_mem = 256MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 1747kB
      huge_pages = off
      min_wal_size = 2GB
      max_wal_size = 8GB

      listen_addresses = '*'

      # Log All Statements
      log_statement = 'all'                      # Logs all SQL statements.
      log_duration = on                          # Logs the duration of each statement.

      # Log Connections and Disconnections
      log_connections = on                       # Logs new client connections.
      log_disconnections = on                    # Logs client disconnections.

      # Log Parameters
      log_parameter_max_length = -1              # Logs full parameter values.
      log_parameter_max_length_on_error = -1     # Logs full parameter values even on errors.

      # Log Execution Plans
      auto_explain.log_min_duration = 0          # Logs execution plans for all queries (requires the auto_explain module).
      auto_explain.log_analyze = on              # Includes actual execution times.
      auto_explain.log_buffers = on              # Logs buffer usage.
      auto_explain.log_timing = on               # Logs timing information.
