services:
  fileserver:
    image: "caddy:latest"
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./data:/data"
      - "./config:/config"

