apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password }}
  SECRET_KEY: {{ .Values.teable.TEABLE_SECRET_KEY }}
  PRISMA_DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Namespace }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  BACKEND_CACHE_REDIS_URI: redis://default:{{ .Values.redis.auth.password }}@{{ .Release.Namespace }}-redis-master:6379/0
