apiVersion: batch/v1
kind: Job
metadata:
  name: teable-db-migrate
spec:
  template:
    spec:
      containers:
      - name: teable-db-migrate
        image: ghcr.io/teableio/teable-db-migrate:latest
        env:
        - name: PRISMA_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Namespace }}-secrets
              key: PRISMA_DATABASE_URL
      restartPolicy: OnFailure
  backoffLimit: 4
