apiVersion: v2
name: lets-encrypt
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: "v1.16.2"
    repository: https://charts.jetstack.io 
